language: php

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.4

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

addons:
  sonarcloud:
    organization: 'ynov'
    token: 'Rye1vOPXYHm5JTWvG08QZVMqUHoP2sm4Xj6pPt+UStHuknRuJheZ45n8geDCMOnlKfxN4CmDJM4wnVHv+CHAJJ0wn3hr4LgfOWA8eCyRd/r3DnFFpSFCa2XEL6eLxLTEhIV50GonByLecYoZlBr/4Rdk9WoklWX+hbF7TDNctpC01cHZB8O6LmG8T4CkW3XwVpkudEo6tpHFLBXNX+iRgFXuef22T8cdDCXHtGIUweCzK/TMmvmz6X7NoxF48PCbUAgRgbfctjIjm4ZTeM+zPLtuRAX3uRcwP7VBumA9cT1dK6pOQ/q9sQubPSYVCOAHOXs013fmB5JhcezdStzFxd3UkJwLkneHNGA8uRjW/koW5y1K1hyu42jxD9xWff757nzxjRkQy00+uWIIU9D8yvkdsZ+BfTHI7wpoiXGly6RC+H4QGuiBRIzewxHx0domgINGnWDM5sO8velKn/EP/n4iZIoRthbXDu5Mm/RPdvt3TxuLDQd1FBmmqNpR+ahmD/ZNldZu2bPDOlakQiCr9Cnz0AGZDYgVyZDC+RFkJh+xDwZyaef6bBtBbyhBlqwETn3ddBVdxiQs6BPXAB9Sl5qaJF0DSAmxp0s7r2Nk2ne+w4I2Uto03tGGaPEoYIpVByEkIyooje+/FRfimKO5MPqXnkbfPSZ9sb6qmt3vVRk='

script:
  - cd docker
  - docker-compose up -d
  - sonar-scanner
  - docker-compose exec react bash -c "npm run test"
  - docker-compose exec apache-php bash -c "php bin/console d:s:u --force"
  - docker-compose exec apache-php bash -c "./vendor/bin/simple-phpunit"

