easy_admin:
  site_name: '<img src="https://i.ibb.co/mH7L5p3/soci-01-3x.png" alt="Logo du site concerto" width="36" border="0"> Concerto <em style="font-size: 80%;">19</em>'
  list:
    max_results: 30
  show:
    max_results: 10
  user:
    display_name: true
    display_avatar: true
    avatar_property_path: 'picture.path'
  design:
    brand_color: '#ff6633'
    assets:
      favicon: '/assets/favicon.png'
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - 'admin/form.html.twig'
    menu:
      - label: 'Services'
        children:
          - { entity: 'Favor', icon: 'gift' }
          - { entity: 'Request', icon: 'handshake' }
      - { entity: 'Category', icon: 'list-ul' }
      - { entity: 'Comment', icon: 'comments' }
      - { entity: 'Picture', icon: 'images' }
      - { entity: 'User', icon: 'user-friends' }
  formats:
    date:     'd/m/Y'
    time:     'H:i'
    datetime: 'd/m/Y H:i:s'
  entities:
    # List the entity class name you want to manage
    Favor:
      class: App\Entity\Favor
      label: 'Propositions'
      list:
        help: 'Sont listés ici tous les services qui ont été proposés par la communauté'
        fields:
          - id
          - { property: 'category', label: 'Catégorie' }
          - { property: 'title', label: 'Titre' }
          - { property: 'content', label: 'Contenu' }
          - { property: 'cities', label: 'Villes' }
          - { property: 'dateStart', label: 'Date de début' }
          - { property: 'dateEnd', label: 'Date de fin' }
          - { property: 'status', label: 'Status' }
          - { property: 'users', label: 'Bénéficiaires' }
          - { property: 'updatedAt', label: 'Dernière modification' }
      form:
        fields:
          - { property: 'title', label: 'Titre' }
          - { property: 'category', label: 'Catégorie' }
          - { property: 'content', label: 'Contenu' }
          - { property: 'placeLimit', label: 'Limite de places' }
          - { property: 'dateStart', label: 'Date de début' }
          - { property: 'dateEnd', label: 'Date de fin' }
          - property: 'users'
            label: 'Bénéficiaires'
            type: 'collection'
            type_options:
              entry_type: 'App\Form\FavorUserEmbeddedFormType'
              allow_delete: true
              allow_add: true
              by_reference: false
          - { property: 'status', label: 'Status', type_options: { block_name: 'custom_status' } }
    Request:
      class: App\Entity\Request
      label: 'Demandes'
      list:
        help: 'Sont listés ici tous les services qui ont été demandés par la communauté'
        fields:
          - id
          - { property: 'user', label: 'Demandeur' }
          - { property: 'title', label: 'Titre' }
          - { property: 'content', label: 'Contenu' }
          - { property: 'dateStart', label: 'Date de début' }
          - { property: 'dateEnd', label: 'Date de fin' }
          - { property: 'updatedAt', label: 'Dernière modification' }
      form:
        fields:
          - { property: 'title', label: 'Titre' }
          - { property: 'content', label: 'Contenu' }
          - { property: 'cities', label: 'Villes' }
          - { property: 'dateStart', label: 'Date de début' }
          - { property: 'dateEnd', label: 'Date de fin' }
    Category:
      class: App\Entity\Category
      label: 'Catégories'
      list:
        fields:
          - { property: 'name', label: 'Nom de la catégorie' }
          - { property: 'updatedAt', label: 'Dernière modification' }
          - { property: 'favors', label: 'Services' }
          - { property: 'picture.path', label: '', type: 'image' }
      form:
        fields:
          - { property: 'name', label: 'Nom de la catégorie' }
          - { property: 'picture', label: 'Image principale' }
    Comment:
      class: App\Entity\Comment
      label: 'Commentaires'
      list:
        fields:
          - id
          - { property: 'user', label: 'Auteur' }
          - { property: 'content', label: 'Contenu' }
          - { property: 'request', label: 'Demande' }
          - { property: 'favor', label: 'Service' }
          - { property: 'updatedAt', label: 'Dernière modification' }
      form:
        fields:
          - { property: 'user', label: 'Auteur' }
          - { property: 'content', label: 'Contenu' }
          - { property: 'request', label: 'Demande' }
          - { property: 'favor', label: 'Service' }
    Picture:
      class: App\Entity\Picture
      label: 'Images'
      list:
        fields:
          - id
          - { property: 'name', label: 'Nom' }
          - { property: 'originalName', label: 'Nom original' }
          - { property: 'path', label: 'URL', type: 'url' }
          - { property: 'favor', label: 'Service' }
          - { property: 'request', label: 'Demande' }
          - { property: 'updatedAt', label: 'Dernière modification' }
          - { property: 'preview', label: '', type: 'image' }
    User:
      class: App\Entity\User
      label: 'Utilisateurs'
      list:
        fields:
          - id
          - { property: 'email', label: 'Adresse e-mail', type: 'email' }
          - { property: 'lastname', label: 'Nom' }
          - { property: 'firstname', label: 'Prénom' }
          - { property: 'birthdate', label: 'Anniversaire' }
          - { property: 'phone', label: 'Téléphone', type: 'tel' }
          - { property: 'updatedAt', label: 'Dernière modification' }
          - { property: 'isAdmin', label: 'Admin' }
          - { property: 'favors', label: 'Services bénéficiés' }
          - { property: 'requests', label: 'Services proposés' }
          - { property: 'picture.path', label: '', type: 'avatar', is_image_url: 'true' }
      form:
        fields:
          - { property: 'email', label: 'Adresse e-mail', type: 'email' }
          - { property: 'password', label: 'Password', type: 'password' }
          - { property: 'lastname', label: 'Nom' }
          - { property: 'firstname', label: 'Prénom' }
          - { property: 'birthdate', label: 'Anniversaire', type: 'App\Form\CustomDateType' }
          - { property: 'phone', label: 'Téléphone' }
          - property: 'favors'
            label: 'Services'
            type: 'collection'
            type_options:
              entry_type: 'App\Form\UserFavorEmbeddedFormType'
              allow_delete: true
              allow_add: true
              by_reference: false
          #                            block_name: 'custom_user_collection'
          - { property: 'requests', label: 'Demandes' }
          - { property: 'picture', label: 'Photo de profil' }
          - { property: 'isAdmin', label: 'Administrateur' }
