version: '3'

services:
  database:
    container_name: ${APP_NAME}_mysql
    image: ${APP_NAME}_mysql
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql


  apache-php:
    container_name: ${APP_NAME}_back
    image: ${APP_NAME}_back
    build:
      context: ./apache-php
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ./back:/app
      - ./logs:/var/log
    ports:
      - "80:80"

  react:
    container_name: ${APP_NAME}_front
    image: ${APP_NAME}_front
    build:
        context: ./react
    ports:
        - 3000:3000
    volumes:
      - ./front:/app/
      - /app/node_modules
