FROM php:7.4-apache

#COPY wait-for-it.sh /usr/bin/wait-for-it
#RUN chmod +x /usr/bin/wait-for-it

RUN apt-get update -y
RUN apt-get install -y

COPY --from=composer /usr/bin/composer /usr/bin/composer

ADD conf/vhost.conf /etc/apache2/sites-available/000-default.conf

RUN docker-php-ext-install pdo_mysql

WORKDIR /app

CMD composer install

#RUN chmod +x bin/console

#RUN php bin/console d:d:c

#RUN php bin/console d:s:u --force

EXPOSE 80
